{{- if .Values.rbac.pspEnabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "helm-operator.psp.name" . }}
  labels:
    app: {{ include "helm-operator.name" . }}
    chart: {{ include "helm-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    rule: RunAsAny
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - configMap
  - emptyDir
  - secret
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "helm-operator.clusterrole.psp.name" . }}
  labels:
    app: {{ include "helm-operator.name" . }}
    chart: {{ include "helm-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
    - apiGroups: ['policy']
      resources: ['podsecuritypolicies']
      verbs:     ['use']
      resourceNames:
        - {{ template "helm-operator.psp.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: {{ template "helm-operator.rolebinding.psp.name" . }}
    labels:
        app: {{ include "helm-operator.name" . }}
        chart: {{ include "helm-operator.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ template "helm-operator.clusterrole.psp.name" . }}
subjects:
    - kind: ServiceAccount
      name: {{ template "helm-operator.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
{{- end }}
