{{- if and .Values.rbac.create (eq .Values.clusterRole.create true) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "helm-operator.clusterRoleName" . }}
  labels:
    app: {{ template "helm-operator.name" . }}
    chart: {{ template "helm-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  # Allow access to the CRD
  - apiGroups: ["helm.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["helm.fluxcd.io"]
    resources: ["helmreleases/status"]
    verbs: ["create", "patch", "update"]
  - apiGroups: ["", "events.k8s.io"]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
{{ .Values.rbac.rules | toYaml | indent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "helm-operator.clusterRoleName" . }}
  labels:
    app: {{ template "helm-operator.name" . }}
    chart: {{ template "helm-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "helm-operator.clusterRoleName" . }}
subjects:
  - name: {{ template "helm-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
    kind: ServiceAccount
{{- end -}}
