{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "helm-operator.serviceAccountName" . }}
  labels:
    app: {{ template "helm-operator.name" . }}
    chart: {{ template "helm-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
